Added 24H or 12H time format options
janoamaral/tokyo-night-tmux pull request #48
Opened 2024-03-22 22:25 UTC by AustinCGause

## Minor changes

- Adds a config option that allows for the selection of either 12H or 24H time formats

## Additional informations

Keeps the default time format of 24H, but allows users to update their configuration to be 12H time format with AM/PM identifier.

2024-03-24 14:04 UTC, janoamaral requested changes
First, thanks for your contribution! I believe that we should make time indicator an independent widget. You are almost there in fact. If you move date and rename `time-format.sh` to `time-widget.sh` I'll merge it

2024-03-24 14:04 UTC, janoamaral commented on src/time-format.sh
> +    echo "%I:%M %p"
show date and time `#[fg=#a9b1d6,bg=#24283B] %Y-%m-%d #[]❬ %I:%M %p`

2024-03-24 14:04 UTC, janoamaral commented on src/time-format.sh
> +    echo "%H:%M"
show date and time `#[fg=#a9b1d6,bg=#24283B] %Y-%m-%d #[]❬ %H:%M`

2024-03-24 14:04 UTC, janoamaral commented on tokyo-night.tmux
> +tmux set -g status-right "$cmus_status#[fg=#a9b1d6,bg=#24283B]$netspeed$git_status$wb_git_status#[fg=#a9b1d6,bg=#24283B]  %Y-%m-%d #[]❬ $time_format_string "
replace `[fg=#a9b1d6,bg=#24283B] %Y-%m-%d #[]❬ $time_format_string ` with `$time_widget`

2024-03-24 17:46 UTC, AustinCGause commented
I have adjusted the date and time formatting to be a separate widget and have updated the README to reflect the new changes. Feel free to let me know if I need to adjust anything else. I have tested the changes and they work correctly.

2024-03-24 17:48 UTC, AustinCGause commented
I apologize, I missed the comment about the option for enabling and disabling, I will implement it.

2024-03-24 18:32 UTC, AustinCGause commented
I have tested the new logic as well, and everything is working as intended, please let me know if there are any adjustments that need to be made.

2024-03-25 21:19 UTC, janoamaral requested changes
Fix those 2 comments and we are good to go

2024-03-25 21:19 UTC, janoamaral commented on tokyo-night.tmux
> +tmux set -g status-right "$cmus_status#[fg=#a9b1d6,bg=#24283B]$netspeed$git_status$wb_git_status$date_and_time "
remove extra space after `$date_and_time`

2024-03-25 21:19 UTC, janoamaral commented on src/datetime-widget.sh
> +echo "#[fg=#a9b1d6,bg=#24283B] $date_string #[]❬ $time_string"
add an extra space after `$time_string`

2024-03-25 22:17 UTC, AustinCGause commented
I have resolved your comments, but also, sorry if this is a bit of a noob question, but what does "resolve conversation" mean/do on the comment's that you added? Is it standard practice to click that after fixing what the comments refer to? Just curious for future reference.

2024-03-26 00:18 UTC, janoamaral approved these changes

2024-03-26 00:18 UTC, merged